package com.preporukaOK.rules.rulesQueryKomadOdece

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.Set;
import java.util.HashMap;
import com.ftn.PreporukaOdevneKombinacije.model.*;
import com.ftn.PreporukaOdevneKombinacije.model.drlModel.*;
import com.ftn.PreporukaOdevneKombinacije.model.enums.*;
import com.ftn.PreporukaOdevneKombinacije.dto.*;

query "getDelovi" (Class klasa)
	$komad : KomadOdece( class == klasa );
end

query "getKomadOdeceByMaterijal" (Materijal mat)
	$komad : KomadOdece( materijal == mat);
end

query "getKomadOdeceByBoja" (Boja b)
	$komad : KomadOdece( boja == b);
end

query "getGornjiDeoByTip" (GornjiDeoEnum b)
	$komad : GornjiDeo( odecaTip == b);
end

query "getDonjiDeoByTip" (DonjiDeoEnum b)
	$komad : DonjiDeo( odecaTip == b);
end

query "getJaknaByTip" (JaknaEnum b)
	$komad : Jakna( odecaTip == b);
end

query "getObucaByTip" (ObucaEnum b)
	$komad : Obuca( obucaTip == b);
end

query "getGornjiDeoByPodTip" (OdecaPodTip b)
	$komad : GornjiDeo( odecaPodTip == b );
end

query "getDonjiDeoByPodTip" (OdecaPodTip b)
	$komad : DonjiDeo( odecaPodTip == b);
end

query "getJaknaByPodTip" (OdecaPodTip b)
	$komad : Jakna( odecaPodTip == b);
end

query "getOdecaByPol" (Pol b)
	$komad : KomadOdece( pol == b);
end

rule "Izbrisi unet komad"
    when
        $ulaz : KomadOdece()
    then
        delete($ulaz)
end
