package com.preporukaOK.rules.rulesCepOdbijen

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.Set;
import java.util.HashSet;
import java.util.HashMap;
import com.ftn.PreporukaOdevneKombinacije.model.*;
import com.ftn.PreporukaOdevneKombinacije.model.drlModel.*;
import com.ftn.PreporukaOdevneKombinacije.model.enums.*;
import com.ftn.PreporukaOdevneKombinacije.model.event.*;
import com.ftn.PreporukaOdevneKombinacije.dto.*;

declare window petdana
	@doc("Odbijanja poslednjih 5 dana")
	OdbijenKomadEvent() over window:time( 5d )
end



rule "Odbijen tri puta poslednjih 5 dana"
    salience 100
    agenda-group "deaktiviranje"
	when
		$odbijeni : OdbijenKomadEvent( $komadOdece : komadOdece );
		$k : KomadOdece( id == $komadOdece.getId(), aktivan == true);
		Number(this >= 3) from accumulate(
        			OdbijenKomadEvent( komadOdece.getId() == $komadOdece.getId()) from window petdana,
        			count( 1 )
        		);
	then
        insert(new DeaktiviranKomadEvent($k));
        modify($k) {setAktivan(false);}
        System.out.println("Deaktiviran komad : " + $komadOdece.getId());
end

rule "Aktiviraj komad 14 dana posle deaktivacije"
    salience 100
    agenda-group "aktiviranje"
when
    $k : KomadOdece( $id : id);
    //not DeaktiviranKomadEvent( komad.getId() == $id );
    List( size == 0 ) from collect(DeaktiviranKomadEvent( komad.getId() == $id ));
then
    modify($k) {setAktivan(true);}
    System.out.println("Aktiviran komad : " + $id);
end

rule "Izbrisi unet komad"
    salience -100
    when
        $ulaz : KomadOdece()
    then
        delete($ulaz)
        System.out.println("Obrisan ulaz");
end